apiVersion: v1
kind: ConfigMap
metadata:
  name: search-replace-fn-config
data:
  by-value: cassandra-0.cassandra.default.svc.cluster.local
  put-value: cassandra-0.cassandra.sdcore4g-cp.svc.cluster.local
