---
# Source: omec-control-plane/templates/service-spgwc.yaml
apiVersion: v1
kind: Service
metadata:
  name: spgwc
  labels:
    release: sdcore4g
    app: spgwc
spec:
  type: ClusterIP
  selector:
    release: sdcore4g
    app: spgwc
  ports:
  - name: s11
    port: 2123
    protocol: UDP
  - name: pfcp
    port: 8805
    protocol: UDP
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
  - name: rest
    port: 8080
    protocol: TCP
