---
# Source: omec-control-plane/templates/service-hss.yaml
apiVersion: v1
kind: Service
metadata:
  name: hss
  namespace: omec
  labels:
    release: sdcore4g
    app: hss
spec:
  type: ClusterIP
  selector:
    release: sdcore4g
    app: hss
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  - name: config-port
    port: 8080
    protocol: TCP
  - name: prometheus-exporter
    port: 9089
    protocol: TCP
