---
# Source: bess-upf/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf
  namespace: omec
  labels:
    release: upf
    app: upf
spec:
  type: ClusterIP
  selector:
    release: upf
    app: upf
  ports:
  - name: pfcp
    protocol: UDP
    port: 8805
---
# Source: bess-upf/templates/service-upf.yaml
apiVersion: v1
kind: Service
metadata:
  name: upf-http
  namespace: omec
  labels:
    release: upf
    app: upf
spec:
  type: ClusterIP
  selector:
    release: upf
    app: upf
  ports:
  - name: bess-web
    protocol: TCP
    port: 8000
  - name: prometheus-exporter
    protocol: TCP
    port: 8080
