apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata: # kpt-merge: /n4
  name: n4
  annotations:
    nephio.org/network-name: n4
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.spgwc-example
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: vpc-internal
  cniType: macvlan
  attachmentType: vlan
