apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: namespace
    fieldPath: data.namespace
  targets:
  - select:
      kind: ServiceAccount
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Role
    fieldPaths:
    - metadata.namespace
  - select:
      kind: StatefulSet
    fieldPaths:
    - metadata.namespace
  - select:
      kind: Service
    fieldPaths:
    - metadata.namespace
 
