---
# Source: bess-upf/templates/statefulset-upf.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: upf
  labels:
    release: upf
    app: upf
spec:
  replicas: 1
  serviceName: upf-headless
  selector:
    matchLabels:
      release: upf
      app: upf
  template:
    metadata:
      labels:
        release: upf
        app: upf
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "access-net",
            "interface": "access",
            "ips": []
          },
          {
            "name": "core-net",
            "interface": "core",
            "ips": []
          }
        ]'
    spec:
      shareProcessNamespace: true
      imagePullSecrets:
        - name: aether.registry
      initContainers:
      - name: bess-init
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "-xec"]
        args:
        - ip route replace 192.168.251.0/24 via ;
          ip route replace default via  metric 110;
          iptables -I OUTPUT -p icmp --icmp-type port-unreachable -j DROP;
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          limits:
            cpu: 128m
            memory: 64Mi
          requests:
            cpu: 128m
            memory: 64Mi
      containers:
      - name: bessd
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        stdin: true
        tty: true
        command: ["/bin/bash", "-xc"]
        args:
          - bessd -m 0 -f -grpc-url=0.0.0.0:10514
        lifecycle:
          postStart:
            exec:
              command: ["/etc/bess/conf/bessd-poststart.sh"]
        livenessProbe:
          tcpSocket:
            port: 10514
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 2
            memory: 1Gi
          limits:
            cpu: 2
            memory: 1Gi
        env:
          - name: CONF_FILE
            value: /etc/bess/conf/upf.json
        volumeMounts:
          - name: shared-app
            mountPath: /pod-share
          - name: configs
            mountPath: /etc/bess/conf
      - name: routectl
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
        command: ["/opt/bess/bessctl/conf/route_control.py"]
        args:
          - -i
          - access
          - core
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 256m
            memory: 128Mi
      - name: web
        image: "omecproject/upf-epc-bess:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/bash", "-xc", "bessctl http 0.0.0.0 8000"]
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 256m
            memory: 128Mi
      - name: pfcp-agent
        image: "omecproject/upf-epc-pfcpiface:master-5786085"
        imagePullPolicy: "IfNotPresent"
        command: ["pfcpiface"]
        args:
          - -config
          - /tmp/conf/upf.json
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 256m
            memory: 128Mi
        volumeMounts:
          - name: shared-app
            mountPath: /pod-share
          - name: configs
            mountPath: /tmp/conf
      - name: arping
        image: "registry.aetherproject.org/tools/busybox:stable"
        imagePullPolicy: "IfNotPresent"
        command: ["sh", "-xc"]
        args:
          - |
            while true; do
              # arping does not work - BESS graph is still disconnected
              #arping -c 2 -I access 
              #arping -c 2 -I core 
              ping -c 2 
              ping -c 2 
              sleep 10
            done
        resources:
          limits:
            cpu: 128m
            memory: 64Mi
          requests:
            cpu: 128m
            memory: 64Mi
      volumes:
      - name: configs
        configMap:
          name: upf
          defaultMode: 493
      - name: shared-app
        emptyDir: {}
