apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omec
  name: sdcore4g-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sdcore4g-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      name: sdcore4g-operator
      labels:
        app.kubernetes.io/name: sdcore4g-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: sdcore4g-operator
      containers:
      - name: kube-rbac-proxy
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
      - name: operator
        image: docker.io/amitinfo2k/sdcore-operator-go:0.1.2
        command:
        - /manager
        args:
        - --leader-elect
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
